joy_teleop:
  ros__parameters:
    axis_linear:
      x: 1
      y: 0
    scale_linear:
      x: 0.2
      y: 0.15
    scale_linear_turbo:
      x: 0.3
      y: 0.225
    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 1.57
    scale_angular_turbo:
      yaw: 2.0
    require_enable_button: false
    enable_turbo_button: 10  # R1 shoulder button
    
#    ps3:
#      axes:
#        x: 0 # left joystick left-right
#        y: 1 # left joystick up-down
#        z: 3 # right joystick left-right
#        rz: 4 # right joystick up-down
#        r2: 5
#        l2: 2
#        left_right: 6 # right side buttons
#        up_down: 7 # right side buttons
#      buttons:
#        cross: 0 # A in Stadia/PS3
#        circle: 1 # B in Stadia/PS3
#        square: 2 # X in Stadia/PS3
#        triangle: 3 # Y in Stadia/PS3
#        l1: 4 # does not work
#        r1: 5
#        select: 6
#        start: 7
#        controller: 8
#        ljoy: 9
#        rjoy: 10