joy_mode_handler:
  ros__parameters:
    joystick: ps4
    estop_button: 9 # L1 shoulder button
    auto_button: 0 # X button

#    ps4:
#      axes:
#        x: 0 # left joystick left-right
#        y: 1 # left joystick up-down
#        z: 2 # right joystick left-right
#        rz: 3 # right joystick up-down
#        l2: 4
#        r2: 5
#      buttons:
#        cross: 0
#        circle: 1
#        square: 2
#        triangle: 3
#        share: 4
#        playstation: 5
#        options: 6
#        ljoy: 7 # left joystick button
#        rjoy: 8 # right joystick button
#        l1: 9
#        r1: 10
#        up: 11
#        down: 12
#        left: 13
#        right: 14
#        trackpad: 15