joy_teleop:
  ros__parameters:
    axis_linear:
      x: 1 # Ljoy front/back
      y: 0 # Ljoy left/right
    scale_linear:
      x: 0.2
      y: 0.15
    scale_linear_turbo:
      x: 0.3
      y: 0.225
    axis_angular:
      yaw: 2 # Rjoy left/right
    scale_angular:
      yaw: 1.57
    scale_angular_turbo:
      yaw: 2.0
    require_enable_button: false
    enable_turbo_button: 5  # R1 shoulder button
