joy_teleop:
  ros__parameters:
    axis_linear:
      x: 1
      y: 0
    scale_linear:
      x: 0.2
      y: 0.15
    scale_linear_turbo:
      x: 0.3
      y: 0.225
    axis_angular:
      yaw: 2
    scale_angular:
      yaw: 1.57
    scale_angular_turbo:
      yaw: 2.0
    require_enable_button: false
    enable_turbo_button: 5  # R1 shoulder button
    
#    stadia:
#      axes:
#        x: 0 # left joystick left-right
#        y: 1 # left joystick up-down
#        z: 2 # right joystick left-right
#        rz: 3 # right joystick up-down
#        r2: 4
#        l2: 5
#        left_right: 6 # right side buttons
#        up_down: 7 # right side buttons
#      buttons:
#        cross: 0 # A in Stadia/PS3
#        circle: 1 # B in Stadia/PS3
#        square: 2 # X in Stadia/PS3
#        triangle: 3 # Y in Stadia/PS3
#        l1: 4
#        r1: 5
#        options: 6
#       menu: 7
#        stadia: 8
#        ljoy: 9
#        rjoy: 10
#        assistant: 11
#        capture: 12
#        r2_digital: 13
#        l2_digital: 14
#        mystery1: 15
#        mystery2: 16
#        mystery3: 17
        
        